export const rules={
  name:[{
    required:true,
    message:'用户名必须输入',
    trigger:'blur'
  },{
    pattern:/^[a-zA-Z0-9]{5,10}$/,
    message:'用户名必须为5-10个字母或数字',
    trigger:'blur'
  }],
  password:[{
    required:true,
    message:'密码必须输入',
    trigger:'blur'
  },{
    pattern:/^[a-zA-Z0-9]{3,}$/,
    message:'密码必须为3个字母或数字以上',
    trigger:'blur'
  }]
}